### ISSUE TITLE
Flash uploads not working

### ISSUE THREAD

**Issue by dvdmierden** [pixeline/bugs#161]
Hi, With more and more browsers disabling Flash functionality lately, the swf uploadify function doesn't work for all users anymore.

Is there a way to replace this with an html5 alternative? I've tried just removing uploadify and making the form accept multipart formdata, but that doesn't work; the file is never attached to the comment or issue.

**Comment by Patriboom** [comment]
Thanks for comment.
I'm just having back my computer working (lost my HDD for no reason).
I'll try to have a look on that soon.

**Comment by Patriboom** [comment]
Hello everyone, 
I'm almost there: attaching file to issue with nothing else than xtthp

Make sure you upted your database which must include
table: 
```
CREATE TABLE IF NOT EXISTS `activity` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `description` varchar(255) character set UTF8 default NULL,
  `activity` varchar(255) character set UTF8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

```
data:
```
INSERT IGNORE INTO `activity` (`id`, `description`, `activity`)
VALUES
	(1,'Opened a new issue','create-issue'),
	(2,'Commented on a issue','comment'),
	(3,'Closed an issue','close-issue'),
	(4,'Reopened an issue','reopen-issue'),
	(5,'Reassigned an issue','reassign-issue'),
	(6,'Updated issue tags','update-issue-tags'),
	(7,'Attached a file to issue','attached-file');

```

**Comment by Patriboom** [comment]
Also, be ready for that, having a 

**app/assets/images/icons/file_01.png**  file like the one attached here.

![file_01](https://user-images.githubusercontent.com/19801202/31042179-13255820-a570-11e7-8a3f-05ea78717461.png)

**Comment by Patriboom** [comment]
Everythings work good in editing issue.
Now, miss to give capability to attach file to a new issue.

**Comment by Patriboom** [comment]
Here we are, pull number 169
https://github.com/pixeline/bugs/pull/169

**Comment by Hazaels** [comment]
So... what should I do?
Do the change on the DB manually?
As far as I understand it will fix the attachment button only when "editing issue" (on browsers like MS-Edge that do not have flash).
But it will not fix when we are "creating a new issue"?

**Comment by Patriboom** [comment]
Since yesterday,  yes it does also for new issue.
If not ... just add your first comment and then attach a file.
The new attaching file system attaches files to issue without any reference to a comment.  Only date and time sort items from oldest to newest (comments, tags, attached files all together).

**Comment by Hazaels** [comment]
But what I don't understand is: What will help to add one row on the database? How that will fix the flash button?
Something is missing... are you sure nothing else was changed on the code?

**Comment by Patriboom** [comment]
![capture](https://user-images.githubusercontent.com/19801202/31106273-666732f2-a7b8-11e7-88c4-b70912b1cb8c.png)

Are you talking about the button shown by the arrow or about another one ? 

The button shown up here is deeply different from what it was before.
I worked many hours on it; I can say you the button has only the same shape and look, but what is « under » is very different.

**Comment by Patriboom** [comment]
It now gives you attached files along the issue's history.
I first took of the file's name insertion out of the comment, but i put it back.
You can see that below.
![capture-1](https://user-images.githubusercontent.com/19801202/31106346-13425f06-a7b9-11e7-9bb4-7b8b92592893.png)

**Comment by Patriboom** [comment]
Most of the changes are visibles here: https://github.com/pixeline/bugs/commit/307392626d0221cb2791ef7e6adcbb94ad1ac2db

**Comment by Hazaels** [comment]
I found a problem... since Bugs is installed in a separate folder inside my website (for example: www.site.com/bugs) then it creates a problem because it looses the path.

Could be that the problem is because you set the folders absolute when they should be relative?

**Comment by marcelloinfoweb** [comment]
I found the some problem.

**Comment by marcelloinfoweb** [comment]
After that I send it by uploading the file does not writes to the database as it should, and appears that way.

![problem_upload_bugs](https://user-images.githubusercontent.com/2093128/31132567-76717254-a833-11e7-95e0-142b3508c4f9.png)

**Comment by Patriboom** [comment]
Thanks for screnshot.  It talks lot more than « Doesn't work for me »
I'll have a look on that.

How did you get such results?  
Is it after addition into a new issue or into a running issue  ? 
It seams to be into a new issue.  Did you use the following page or an other one ? 
**index.php/project/PRnum/issue/new**

**Comment by Patriboom** [comment]
What do you think about this idea:
  -to include a question about the absolute path into the install process ?

**Comment by Hazaels** [comment]
I think it is not necessary... it should only use relative paths and should work automatically in any case:

1. www.bugs.com
2. www.site.com/bugs
3. www.site.com/tool/bugs

Above are 3 diferent possible cases... should work in all.

**Comment by Hazaels** [comment]
Ops... now I can't even enter in bugs...
I get the following error:

Unhandled Exception
Message:
Error rendering view: [activity/attached-file]
Undefined offset: 0
Location:
/home3/sysbasef/public_html/bugs/app/application/views/activity/attached-file.php on line 9
Stack Trace:
#0 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined offse...', '/home3/sysbasef...', 9)
#1 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(9): Laravel{closure}(8, 'Undefined offse...', '/home3/sysbasef...', 9, Array)
#2 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#3 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#4 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#5 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(39): Laravel\View->__toString()
#6 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#7 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#8 /home3/sysbasef/public_html/bugs/app/laravel/view.php(438): Laravel\View->render()
#9 /home3/sysbasef/public_html/bugs/app/laravel/view.php(363): Laravel\View->data()
#10 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#11 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#12 /home3/sysbasef/public_html/bugs/app/laravel/response.php(246): Laravel\View->__toString()
#13 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(177): Laravel\Response->render()
#14 /home3/sysbasef/public_html/bugs/index.php(19): require('/home3/sysbasef...')
#15 {main}

Please look the attached image (phpMyAdmin)
![screenshot_1](https://user-images.githubusercontent.com/3906754/31154041-c5f21198-a87a-11e7-9318-36757a19c671.jpg)

**Comment by Patriboom** [comment]
I just fixed the problem (line 9), making a patch which handles the NULL values (when error occurs).

**Comment by Hazaels** [comment]
What happens when the attachment has exact the same name?

**Comment by Hazaels** [comment]
I just downloaded bugs again, copied all files back to the server but the error persists:

Unhandled Exception
Message:
Error rendering view: [activity/attached-file]

Undefined offset: 0
Location:
/home3/sysbasef/public_html/bugs/app/application/views/activity/attached-file.php on line 8
Stack Trace:
#0 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined offse...', '/home3/sysbasef...', 8)
#1 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(8): Laravel\{closure}(8, 'Undefined offse...', '/home3/sysbasef...', 8, Array)
#2 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#3 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#4 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#5 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376) : eval()'d code(39): Laravel\View->__toString()
#6 /home3/sysbasef/public_html/bugs/app/laravel/view.php(376): eval()
#7 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#8 /home3/sysbasef/public_html/bugs/app/laravel/view.php(438): Laravel\View->render()
#9 /home3/sysbasef/public_html/bugs/app/laravel/view.php(363): Laravel\View->data()
#10 /home3/sysbasef/public_html/bugs/app/laravel/view.php(344): Laravel\View->get()
#11 /home3/sysbasef/public_html/bugs/app/laravel/view.php(581): Laravel\View->render()
#12 /home3/sysbasef/public_html/bugs/app/laravel/response.php(246): Laravel\View->__toString()
#13 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(177): Laravel\Response->render()
#14 /home3/sysbasef/public_html/bugs/index.php(19): require('/home3/sysbasef...')
#15 {main}

**Comment by Patriboom** [comment]
fixed with a @ on variable evaluation.
Sorry for that.

**Comment by marcelloinfoweb** [comment]
When you put the code down, thought about the possibility of someone using the system on a local server or localhost?

`$PosiPoint = strpos($_SERVER['REQUEST_URI'], ".");`

I'm have this problem:

**Message**:
Undefined offset: 3

**Location**:
/var/www/bugs_/app/application/controllers/project/issue.php on line 376

**Comment by marcelloinfoweb** [comment]
Is there anything new?

**Comment by Patriboom** [comment]
This thread is closed

Please refer to the other one after uptading the following files.

/app/application/view/activity/attached-file
/app/application/view/project/issue/activity/attached-file

**Comment by marcelloinfoweb** [comment]
Man, I already did that and it's still the same, it does not show the attachment in the added comment.

**Comment by Patriboom** [comment]
I'll be back, but for now I'm too busy to work on that.

**Comment by Patriboom** [comment]
Sorry for that longer delay, I had a surgery lately.

**Comment by Patriboom** [comment]
I've just had an overview on the whole story here.
Download needs a /uploads folder strait in the  Bug's main directory like: 
http://127.0.0.1/Tickets/uploads

Give it wide writes like 775
It should belong to the same as apache, most likely  _www-data_, _apache_ or _EasyPHP_ user and group.

**Comment by wycky** [comment]
you mean we create a new folder by the name "downloads "in the main directory or?

**Comment by wycky** [comment]
Don't know whether anybody else has realized that during issue assignment, attachment does not work but during commenting on the issue/ticket if a user can attach a file that is when it can be seen by everyone

**Comment by wycky** [comment]
So far Patrick i have realized file attachments only works for me during issue commenting by parties involved in a project, i will stick to that until i figure out which line of codes i can also add to new issue creation files

**Comment by Patriboom** [comment]
Good ... if you can do that.
On first time, I just said for myself: « Ok, let create the issue and then will add attachment ».  Because I have hard time to work with the Laravel structure and, for the method i introduced for attachement, the system needs the issue's number to store the attachment's informations into database.

**Comment by wycky** [comment]
No.....file is stored with reference of issue_id..its okay with me for now to attach file on issue comment
![db](https://user-images.githubusercontent.com/25264938/34289512-ef2f70c4-e703-11e7-89ec-3b65c7b42c06.png)

**Comment by Patriboom** [comment]
So, your database is ok.  Nice.!

Does it mean that Bugs shows you attached files like  « Patriboom commented on 2 Oct  » ?

**Comment by wycky** [comment]
Yeap...it shows..but still even during commenting at times the file is flashed and at times it fails, so its by lack the file to be flashed before i click comment for it to be submitted to the upload folder.

**Comment by Patriboom** [comment]
Good!  Thanks Valerie

Merry Christmas.


On Fri, 22 Dec 2017 04:45:15 -0800
wycky <notifications@github.com> écrivites:

> Yeap...it shows..but still even during commenting at times the file
> is flashed and at times it fails, so its by lack the file to be
> flashed before i click comment for it to be submitted to the upload
> folder.
> 









---

Soyez artisans de paix.

Patrick Allaire, ptre

**Comment by Patriboom** [comment]
I'll consider this issue fixed unless anyone else shows screen shot of what happens on its **Bugs**

**Comment by wycky** [comment]
for me its fixed

**Comment by marcelloinfoweb** [comment]
Still Not Working:

![uploadbugs](https://user-images.githubusercontent.com/2093128/34530956-d649541a-f097-11e7-9e53-0d8040723d59.gif)

**Comment by Patriboom** [comment]
Ok, thanks for video.
I'll have an other look.

**Comment by marcelloinfoweb** [comment]
Explain why you did not use the upload file that already came in the system? Why did you have to create another file?

**Comment by marcelloinfoweb** [comment]
Guys, I tried to do different to update what I already used. Come on, I created another database and renamed the bugs directory, and did the clean install. After installing and testing, I decided to import only the data and not the tables with data, and adapting the inserts, and it worked perfectly. Now, this is perfect and for now I close the question.
Sorry for the inconvenience.

**Comment by Patriboom** [comment]
Wow! What a good news!
That means a new user will have no problem!
Thanks Marcello to let us know.
